// The photographic craft contract for customer campaigns.
//
// WHY THIS EXISTS
//
// The site's own studio imagery is generated by prepending a fixed, tuned photographic spec to
// every prompt (lib/studio/styleContract.ts). That file is the reason those images look like one
// photographer shot them on one day.
//
// The customer pipeline had no equivalent. Its prompts are written at runtime by the analysis
// model, working from master-improvement-logic.txt -- and that document is almost entirely about
// TRUTH: what must be preserved, what may never be invented, what counts as misrepresentation. It
// is a superb honesty policy and says almost nothing about photography. So the image model was
// being handed careful instructions about what not to change and near-zero instruction about how
// the picture should actually look, and it defaulted to what an edit model defaults to: a
// slightly cleaned-up version of the phone snapshot it was given.
//
// This file supplies the missing half. It is deliberately narrower than the studio contract,
// because the two jobs are different:
//
//   studio    invents an item and a room, so it can dictate palette and furnishing.
//   campaign  photographs a REAL item the seller owns, so it must dictate only the photography.
//
// Hence: no palette, no material, no styling language here. Every clause is about camera, light,
// and render quality -- things that are true of the photograph rather than of the object. Anything
// that could restyle the item belongs in the truth lock's forbidden list, not in this file.

/**
 * Shared by both variants. Realism failures are what read as "AI" to a buyer scrolling a
 * marketplace, and they sink a listing faster than an unflattering angle does.
 */
const REALISM = `
RENDER QUALITY -- non-negotiable
Photorealistic throughout. Correct scale, proportion, and perspective; straight verticals; no
warping or fisheye. The item rests convincingly on the floor with a soft-edged contact shadow
where it meets the ground. One coherent light direction across the entire frame.
Real material response: fabric reads as woven fabric with visible weave and nap, wood as wood
with grain, metal as metal with specular highlights, plastic as plastic. Surfaces must not go
smooth, waxy, or plastic-looking -- that melted, airbrushed finish is the single most common
tell that an image was generated, and it is disqualifying here.
Keep small real-world imperfection: fabric creases where a seat has been sat in, slight
irregularity in seams and stitching, minor floor and wall texture. Do not smooth these away.
DEEP FOCUS: the whole frame is in focus, front to back. Do not blur or soften the background.
Simulated shallow depth of field is a second common tell -- a background that is soft but not
optically soft reads instantly as fake. When in doubt, render it sharp.

NEVER INCLUDE
No people, no hands, no pets. No added text, letters, numbers, logos, watermarks, badges, or
signage that is not physically present on the real item. No borders, frames, collages, or split
panels. No graphic overlays or UI elements. No duplicated, floating, or intersecting objects. No
CGI or 3D-render look. No visible generation artefacts.

OUTPUT
A single photograph. Nothing in the frame beyond what is described.
`.trim();

/**
 * Marketing shots: the ones a buyer sees first in the listing carousel. These may be staged in a
 * clean, plausible room -- but the room is the only thing being upgraded.
 */
const MARKETING = `
CAMERA AND LENS
Full-frame mirrorless, 45mm prime at f/8. Natural undistorted perspective, camera at roughly
chest height unless this shot says otherwise. No wide-angle stretch at the frame edges.

LIGHT
Soft, directional daylight from a single large window out of frame to camera-left, around 5200K.
Gentle fill from a pale surface camera-right so shadows stay open and detailed rather than
crushed to black. No hard sun shafts, no visible lamps or fixtures, no coloured gels, no rim
light, no studio strobe look.

EXPOSURE AND FINISH
Accurate white balance and a clean, correct exposure -- bright and open, but never blown out.
Natural contrast with detail held in both highlights and shadows. A trace of fine film-like
grain. No HDR, no glow or bloom, no vignette, no heavy colour grading, no oversaturation.

SETTING
An ordinary, well-kept home -- the kind a real person lives in. Uncluttered but not empty, and
never a showroom or a luxury magazine interior. Plain walls, at most one simple framed print, a
plain floor. If this shot names a specific location, that location replaces this one entirely;
carry the same restraint across to it. Keep the backdrop simple and reasonably close behind the
item; avoid deep views into distant foliage, where rendering breaks down.

${REALISM}
`.trim();

/**
 * Evidence shots: undersides, labels, wear, mechanisms. Staging these is the exact thing the
 * truth policy exists to prevent -- a beautifully lit underside looks like a cover-up. They need
 * to look like a careful person documenting a real object, so the craft spec here is about
 * clarity and legibility, not about atmosphere.
 */
const EVIDENCE = `
THIS IS A DOCUMENTARY SHOT, NOT A STYLED ONE
Its job is to let a buyer verify a fact. It must look like a careful owner documenting their own
item honestly -- not like a catalogue photograph. Do not relocate the item to a nicer room, do not
stage it, and do not make the condition look better than it is.

CAMERA AND LENS
Full-frame mirrorless, 50mm at f/8, square-on to the surface being documented so it is not
distorted by angle. Close enough that the feature in question fills the frame and any real
lettering, wear, or mechanism is plainly legible.

LIGHT
Even, neutral, shadowless illumination across the whole subject -- the goal is that nothing is
hidden. Accurate white balance, correct exposure, open shadows. No dramatic or directional
lighting, no atmosphere, no mood.

WHAT MAY IMPROVE
Only the photography: exposure, white balance, focus, noise, perspective correction, and crop.
The item, its wear, its dirt, its damage, and its surroundings stay exactly as they are.

${REALISM}
`.trim();

/**
 * Wraps a shot prompt in the craft contract.
 *
 * PRECEDENCE MATTERS. The shot prompt carries the truth lock -- the facts about the seller's real
 * item that may not be altered. The contract below is about the photograph only, and is stated to
 * be subordinate in writing, so a clause like "soft daylight" can never be read as licence to
 * restyle a stained grey chair into a clean cream one. The shot prompt is placed last because it
 * is the more specific and more important half.
 */
export function withPhotoContract(
  prompt: string,
  classification: 'marketing' | 'evidence',
  /**
   * True for the modes that edit one existing photo in place (source_edit, hero_edit). Those
   * modes get their value from leaving the frame alone, so the SETTING clause above -- which is
   * written for shots being composed fresh -- has to be switched off or it invites the model to
   * relocate the item and throw away the exact thing the mode was chosen for.
   */
  preserveSetting: boolean,
): string {
  const contract = classification === 'evidence' ? EVIDENCE : MARKETING;
  const pin = preserveSetting
    ? `

SETTING -- OVERRIDE
Ignore the SETTING paragraph above. This shot edits an existing photograph in place. The room,
the ground, the walls, the fixed surroundings, and the camera position all stay exactly as they
already are. Only exposure, white balance, colour accuracy, focus, noise, and unrelated clutter
outside the item's outline may improve.`
    : '';
  return `${contract}${pin}

======================================================================
THE SHOT -- this section outranks everything above it
======================================================================
Everything above describes how the photograph should be MADE. What follows describes the real
object being photographed and the facts about it that must not change. Where the two ever
conflict, what follows wins, without exception. Nothing above authorises altering the item's
shape, colour, materials, hardware, wear, damage, dirt, or completeness.

${prompt}`;
}
